[theme]

# Primary accent for interactive elements
primaryColor = '#A5223C'

# Background color for the main content area
backgroundColor = '#FAF8F4'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#41877C'

# Color used for almost all text
textColor = '#232325'

# Font family for all text in the app, except code blocks
font = "monospace"
