[theme]

# Primary accent for interactive elements
primaryColor = '#1D2D44'

# Background color for the main content area
backgroundColor = '#F7F7F7'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#A5B5D7'

# Color used for almost all text
textColor = '#333333'

# Font family for all text in the app, except code blocks
font = "monospace"
